import React from 'react'

export const Services = () => {
  return (
    <div>
        <div> Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores incidunt, iusto magnam ad sapiente vero officia neque similique rerum enim minus aspernatur, suscipit autem impedit alias non libero delectus, odit commodi nulla? Quibusdam, corrupti magnam. Repellendus cumque amet modi autem veritatis aspernatur commodi nesciunt aliquid odio porro, reprehenderit reiciendis, quo illum consequuntur, ab maiores molestiae ullam! Libero molestias, modi culpa rerum officia repellat repudiandae exercitationem, commodi ut quae quaerat cupiditate! Blanditiis, ratione nihil! Quam nostrum laudantium perspiciatis aliquid error veniam sed architecto natus fuga dolore commodi iure quibusdam, accusantium cum obcaecati exercitationem necessitatibus totam! Inventore consequatur ea neque itaque eligendi. </div> <br/>
        <div> Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores incidunt, iusto magnam ad sapiente vero officia neque similique rerum enim minus aspernatur, suscipit autem impedit alias non libero delectus, odit commodi nulla? Quibusdam, corrupti magnam. Repellendus cumque amet modi autem veritatis aspernatur commodi nesciunt aliquid odio porro, reprehenderit reiciendis, quo illum consequuntur, ab maiores molestiae ullam! Libero molestias, modi culpa rerum officia repellat repudiandae exercitationem, commodi ut quae quaerat cupiditate! Blanditiis, ratione nihil! Quam nostrum laudantium perspiciatis aliquid error veniam sed architecto natus fuga dolore commodi iure quibusdam, accusantium cum obcaecati exercitationem necessitatibus totam! Inventore consequatur ea neque itaque eligendi. </div> <br/>
        <div> Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores incidunt, iusto magnam ad sapiente vero officia neque similique rerum enim minus aspernatur, suscipit autem impedit alias non libero delectus, odit commodi nulla? Quibusdam, corrupti magnam. Repellendus cumque amet modi autem veritatis aspernatur commodi nesciunt aliquid odio porro, reprehenderit reiciendis, quo illum consequuntur, ab maiores molestiae ullam! Libero molestias, modi culpa rerum officia repellat repudiandae exercitationem, commodi ut quae quaerat cupiditate! Blanditiis, ratione nihil! Quam nostrum laudantium perspiciatis aliquid error veniam sed architecto natus fuga dolore commodi iure quibusdam, accusantium cum obcaecati exercitationem necessitatibus totam! Inventore consequatur ea neque itaque eligendi. </div> <br/>
        <div> Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores incidunt, iusto magnam ad sapiente vero officia neque similique rerum enim minus aspernatur, suscipit autem impedit alias non libero delectus, odit commodi nulla? Quibusdam, corrupti magnam. Repellendus cumque amet modi autem veritatis aspernatur commodi nesciunt aliquid odio porro, reprehenderit reiciendis, quo illum consequuntur, ab maiores molestiae ullam! Libero molestias, modi culpa rerum officia repellat repudiandae exercitationem, commodi ut quae quaerat cupiditate! Blanditiis, ratione nihil! Quam nostrum laudantium perspiciatis aliquid error veniam sed architecto natus fuga dolore commodi iure quibusdam, accusantium cum obcaecati exercitationem necessitatibus totam! Inventore consequatur ea neque itaque eligendi. </div> <br/>
        <div> Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores incidunt, iusto magnam ad sapiente vero officia neque similique rerum enim minus aspernatur, suscipit autem impedit alias non libero delectus, odit commodi nulla? Quibusdam, corrupti magnam. Repellendus cumque amet modi autem veritatis aspernatur commodi nesciunt aliquid odio porro, reprehenderit reiciendis, quo illum consequuntur, ab maiores molestiae ullam! Libero molestias, modi culpa rerum officia repellat repudiandae exercitationem, commodi ut quae quaerat cupiditate! Blanditiis, ratione nihil! Quam nostrum laudantium perspiciatis aliquid error veniam sed architecto natus fuga dolore commodi iure quibusdam, accusantium cum obcaecati exercitationem necessitatibus totam! Inventore consequatur ea neque itaque eligendi. </div> <br/>
        <div> Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores incidunt, iusto magnam ad sapiente vero officia neque similique rerum enim minus aspernatur, suscipit autem impedit alias non libero delectus, odit commodi nulla? Quibusdam, corrupti magnam. Repellendus cumque amet modi autem veritatis aspernatur commodi nesciunt aliquid odio porro, reprehenderit reiciendis, quo illum consequuntur, ab maiores molestiae ullam! Libero molestias, modi culpa rerum officia repellat repudiandae exercitationem, commodi ut quae quaerat cupiditate! Blanditiis, ratione nihil! Quam nostrum laudantium perspiciatis aliquid error veniam sed architecto natus fuga dolore commodi iure quibusdam, accusantium cum obcaecati exercitationem necessitatibus totam! Inventore consequatur ea neque itaque eligendi. </div> <br/>
    </div>
  )
}
